### ISSUE TITLE
--active style for a 'tab' resets when changing browser tab

### ISSUE THREAD

**Issue by alxwrd** [tatyshev/pomidorus#1]
Hello! Loving the app. Just wanted to mention a very minor thing I noticed.

If you have the Settings or About tab selected: when changing to a different browser tab the `--active` style resets back to the Timer tab.

![pomidorus](https://user-images.githubusercontent.com/13941027/34668746-a884e0f8-f466-11e7-916e-e2bde9bff89b.gif)

### Happening on:
Firefox: *57.0.4 (64-bit)*
Chrome: *63.0.3239.132 (Official Build) (64-bit)*
IE: *11.1176.10586.0*

**Comment by tatyshev** [comment]
Thanks for the report, fixed in 13a21a3.
