### ISSUE TITLE
Show settings values on mouse hover

### ISSUE THREAD

**Issue by marat93** [tatyshev/pomidorus#2]
Now, to see the current setting value you have to press the slider button. It would be great to see current value just on hover.

![pomidorus setting](https://user-images.githubusercontent.com/6310396/34972610-cbf6affc-faac-11e7-8300-c77b5bebf8a6.png)

**Comment by tatyshev** [comment]
@marat93 Fixed in 1.0.3

https://github.com/tatyshev/pomidorus/releases/tag/1.0.3
